#!/bin/bash -ex

if test -d book; then
    echo "data already downloaded"
else
    wget http://iupr1.cs.uni-kl.de/~tmb/ocropus-data/uw3-500.tgz
    tar -zxvf uw3-500.tgz
fi

ocropus-rtrain 'book/*/*.bin.png' -d 5 -o uw3-500-model
